### ISSUE TITLE
Switching from deprecated requests library to axios

### ISSUE THREAD

**Issue by jimlindeman** [ihsw/toxiproxy-node-client#4]
Is this library deprecated or still active?  We like to continue using toxiproxy in our integration tests for database connectivity-loss/recovery testing but the 'requests' library (deprecated since 2020) that it uses has all sort of red flags in Mend and other scans.   Switching it to use 'axios' should be fairly trivial PR I can make (as we've been doing that switch in our apps).

**Comment by tskvivekmani** [comment]
@ihsw Can you update if anyone working on this regard. Else I would like to contribute.

**Comment by dvag-gloeckner-daniel** [comment]
@ihsw how are the chances of getting a PR merged which replaces the requests library with axios?

**Comment by dvag-gloeckner-daniel** [comment]
Fixed in scope of #6.

**Comment by ihsw** [comment]
@jimlindeman @tskvivekmani this is fixed now, thank you @dvag-gloeckner-daniel
