### ISSUE TITLE
Make library universal to allow running from v8 engines or in-browser tests

### ISSUE THREAD

**Issue by ngbrown** [ihsw/toxiproxy-node-client#5]
When trying to use this library from vitest in-browser, it errors with "process is not defined". Using native `fetch` would allow this to run everywhere.

**Comment by dvag-gloeckner-daniel** [comment]
Fixed in scope of #6. Axios makes this transparent to the user so this library can now be used in Node or in the browser.

**Comment by ihsw** [comment]
@ngbrown this is fixed now, thank you @dvag-gloeckner-daniel
